class CustomError {
  cause?: Error;
  message: string = "error";

  constructor(cause?: Error) {
    this.cause = cause;
  }
}

class LogoutError extends CustomError {
  message = "Logout ha fallado";
}

class LoginError extends CustomError {
  message = "Fallo al iniciar sesi贸n";
}

class BackendError extends CustomError {
  message = "Ocurri贸 un problema con el servidor";
}
class MustLoginAgainError extends CustomError {
  message = "Debe volver a iniciar sesi贸n otra vez";
}

class MustRefreshSessionError extends CustomError {
  message = "Debe volver a revalidar la sesi贸n";
}

export default CustomError;
export {
  LogoutError,
  BackendError,
  MustLoginAgainError,
  MustRefreshSessionError,
  LoginError,
};
